### ISSUE TITLE
Upgrade on eslint and prettier rules

### ISSUE THREAD

**Issue by kaluabentes** [CheesecakeLabs/react-next-boilerplate#3]
My problem is when I try to save a file with the following:

```
import React, { Fragment } from 'react'

import Icon from '_atoms/icon'
```

The auto format on save of editor turns into:

```
import React, { Fragment } from 'react'
import Icon from '_atoms/icon'
```

But the rule of eslint or prettier warning this

**Comment by caiangums** [comment]
On my point of view, imports from `libs` should be spaced from imports from `components` or `styles`, like the eslint/prettier are effective warning and you @kaluabentes are following the same code pattern as me.
There is a specific reason for on format remove the space between imports?

**Comment by kaluabentes** [comment]
I think that the problem with the rule is when it matches `_atom/icon` it thinks that is a `lib` because of the absense of absolute path declaration `./`, so the formartOnSave feature formats thinking that the import is from a third party lib `lib` when its not. I had some warnings about unresolved path to module too.

**Comment by dleitee** [comment]
@kaluabentes I don't think so. Do you know if your IDE has been configured correctly? Because here I save my files and my config is formatting normally.

I guess your IDE is using its own configuration, not the `.prettierrc` from the project.

@kaluabentes could you please double check on it?

@caian-gums do you know if is this occurring on your IDE?

**Comment by caiangums** [comment]
Yes. I'm Using VSCode but maybe my config was wrong. I'll check this and give a feedback.

**Comment by dleitee** [comment]
Already fixed.
