### ISSUE TITLE
Create an generator using Yeoman

### ISSUE THREAD

**Issue by helderberto** [CheesecakeLabs/react-next-boilerplate#39]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Install boilerplate passing some data for the new project via terminal.

**Describe the solution you'd like**
I think an simple generator using [Yeoman](https://yeoman.io/) can solve this issue.

**Describe alternatives you've considered**
[Yeoman](https://yeoman.io/) or another project generator.

**Teachability, Documentation, Adoption, Migration Strategy**
Ex.: yo create-rnb <project-name>

It's going to generate new folder using the project name, and all set titles and description as we configure in yeoman.

**Comment by dleitee** [comment]
I don't think it might be a good idea, so I'm listing some `pros` and cons `here`:

*Pros:*
- we would create the project using a single command.

*Cons:*
- This would generate an over configuration using templates, and would decrease the maintainability of the code.


---

When I created the boilerplate I've created a way to start the project using only a command, like:
```
npx create-ckl-react-app <app-name>
```

but since the npm have growth a lot on the past months, this one was not working anymore, if we want, we can bring back this script

**Comment by helderberto** [comment]
I agree with you. Thanks for the reply!
